notes = {40 : "String 6 - Open   | E  (2)",
         41 : "String 6 - Fret 1 | F  (2)",
         42 : "String 6 - Fret 2 | F# (2)",
         43 : "String 6 - Fret 3 | G  (2)",
         44 : "String 6 - Fret 4 | G# (2)",
         45 : "String 5 - Open   | A  (3)",
         46 : "String 5 - Fret 1 | A# (3)",
         47 : "String 5 - Fret 2 | B  (3)",
         48 : "String 5 - Fret 3 | C  (3)",
         49 : "String 5 - Fret 4 | C# (3)",
         50 : "String 4 - Open   | D  (3)",
         51 : "String 4 - Fret 1 | D# (3)",
         52 : "String 4 - Fret 2 | E  (3)",
         53 : "String 4 - Fret 3 | F  (3)",
         54 : "String 4 - Fret 4 | F# (3)",
         55 : "String 3 - Open   | G  (3)",
         56 : "String 3 - Fret 1 | G# (3)",
         57 : "String 3 - Fret 2 | A  (4)",
         58 : "String 3 - Fret 3 | A# (4)",
         59 : "String 2 - Open   | B  (4)",
         60 : "String 2 - Fret 1 | C  (4)",
         61 : "String 2 - Fret 2 | C# (4)",
         62 : "String 2 - Fret 3 | D  (4)",
         63 : "String 2 - Fret 4 | D# (4)",
         64 : "String 1 - Open   | E  (4)",
         65 : "String 1 - Fret 1 | F  (4)",
         66 : "String 1 - Fret 2 | F# (4)",
         67 : "String 1 - Fret 3 | G  (4)",
         68 : "String 1 - Fret 4 | G# (4)"}

# Tracks that are unplayable on the guitar such as percussion, synth, etc
# Listed in reverse order for easier removal
mute_tracks = {"Africa" : [18, 17, 16, 15, 14, 13, 12, 11, 10, 7, 6],
               "Aladdin": [13, 10],
               "AllNotesTest": [],
               "CountryRoads": [10],
               "Mario": [],
               "Mii": [],
               "OverlappingNotesTest": [],
               "Pirates": [],
               "Rickroll": [],
               "Simpsons": [16, 15],
               "StillDre": [],
               "Tetris": [],
               "Twinkle": [],
               "UnderTheSea": [],
               "VivaLaVida": []}
